on:
  pull_request:
    branches:
      - 'master'
      - 'staging'

name: CI
jobs:
  build-app:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:7.3

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v1

      - name: Install composer dependencies
        run: |
          composer install --optimize-autoloader --no-dev

      - name: Install NPM dependencies
        run: |
          npm i
          npm run prod

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate
          php artisan migrate:fresh
