name: Build App

on:
  pull_request:
    branches:
      - 'master'
      - 'staging'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Shutdown Ubuntu SQL
        run: sudo service mysql stop
      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          - mysql database: 'laravel'
          - mysql user: 'root'
          - mysql root password: ''
      - uses: actions/checkout@v1
      - name: Create database if it dosen't exist
        run: mysql -h 127.0.0.1 --port 3306 -u root -e 'CREATE DATABASE IF NOT EXISTS laravel;'
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Install NPM Dependencies
        run: npm install
      - name: Build NPM files
        run: npm run prod
      - name: Generate key
        run: php artisan key:generate
      - name: Migrate database
        run: php artisan migrate:fresh --seed


