on:
  pull_request:
    branches:
      - 'master'
      - 'staging'

name: CI
jobs:
  build-app:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:7.3

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v1

      - name: Install composer dependencies
        run: |
          composer install

      - name: Install NPM dependencies
        run: |
          npm i
          npm run prod

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate
          php artisan migrate:fresh

      - name: Test Laravel Application
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_SECRET: ${{ secrets.ALGOLIA_SECRET }}
        run: |
          php artisan env:set ALGOLIA_APP_ID "$ALGOLIA_APP_ID" --quiet
          php artisan env:set ALGOLIA_SECRET "$ALGOLIA_SECRET" --quiet
          php artisan scout:sync
          php artisan test
